#cloud-config
hostname: otayouvm
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKDnAezI7H4fvRBegTGugWHn2w4ma/7AF+2f1nElXtUrRTNfj2D+uewsUiEFixmKTdfv3dIL7bozPk5DckfXzogpcOA5Ldd4LO0/F1eYRBhCTe3Y+qAFjDR7wlqsN0z4AIeVyL1CoSxDRVVrtzFn0ww5kFD3FaTyQ1pKTCswQrxGlohY0/7CxTKG6WYLaitMrOiAO85vyRscanrdvaGhMhOf7q/b2na/26a7ozZFX1BVvX1KqZWp1OXbB6b71TZoyo7Dsl4M7sjJTB+X89iCA62mLGYolvIEWaAqmUsmrd571gMRsY7G7Z+ocvSjvwTHfvjzbTpDBjHbjUi9FtPmjepcEjd5YwwMKagnZy28kgu9VpkfnqOvItsXPfagrBQMe/uAG+u8JMYu6XHs3u69kqfd6oca3gz1zAzX357q1A1WUcx45oaLAl0l4f8F9RMDJjEv7yWoC+PGdRh1mdSg+aUJCMfggruazMx4LufmvginZcUf/PLttnYcWclRHaA4Fdg+SBGhBdSYyRX9BmFx6AsugxVndH7lPtGQ5LcGbEKLimgRswVHbSNUKvh0R6/SAEfLLjeFB+KXp7M1QObzed4BvbFru98fkxj8ne0xviGcexKVCx9ZFFmz0wRH36sqU/T50+snHq4/vPEeqNivzg/7uMj5Ysa/2WeWLUX5brtw== root@host1
ssh_pwauth: false

chpasswd:
  list: |
     ubuntu: $6$abcdefgh$randomhashedvalue123456...
  expire: False

packages:
  - python3
  - python3-pip

runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, restart, networking ]

final_message: "Let's GO !!! after $UPTIME seconds"
